### ISSUE TITLE
Piktogramme

### ISSUE THREAD

**Issue by andneuma** [kjoscha/lichtenberg#14]
Neue Issues:

* "Show all" zeigt alle POI allerdings mit dem gleichen Symbol (Firefox)
* Für ‘event room' (soll Veranstaltungsraum bedeuten) brauch es eigentlich ein anderes Symbol, kümmer mich drum

**Comment by andneuma** [comment]
32x32 als strikte Vorgabe ist doof, kannst du das evtl. wieder rausnehmen?Das "free-wifi" ließ sich größengetreu nur auf 32x22 runterscalen.

**Comment by kjoscha** [comment]
ja, das war ein doofer woraround, weil die Icons total doof aussehen, wenn sie on the fly runterskaliert werden. Du kannst sie aber auch auf 32 x 22 skalieren (oder wird es nicht angezeigt?). Es müsste eigentlich einfach in der Originalgröße dargestellt werden...

**Comment by kjoscha** [comment]
achso nee. Du kannst auch Icons in anderen Größen benutzen, diese werden dann auf 32px width runterskaliert und sehen halt evtl. doof aus. Aber das können wir ja erstmal ignorieren...

**Comment by kjoscha** [comment]
Nun Sterne als Default (wenn all!-Button aktiv). Es fehlt noch, dass wirklich alle Features, egal ob es einen entsprechenden Tag gibt, angezeigt werden

**Comment by andneuma** [comment]
Vielleicht kann man den "all!"-Button auch wegnehmen? es macht ja erstmal nicht so viel sinn, sich alles anzeigen zu lassen. Besser fänd ich es fast, wenn man zusätzliche Layer schalten könnte. Aber da kommt man dann sicherlich in Schwierigkeiten, wenn ein POI zu zwei oder mehr Kategorien gehört (Stichwort: Tag-Cloud), oder?

**Comment by kjoscha** [comment]
ich finde es ganz gut einen Button für alles zu haben,  da ich einen use case auch darin sehe, einfach die Umgebung z.B. seines Zuhauses zu erkunden und zu schauen, was es so gibt... das mit den mehreren Layern steht auch der Langzeit-Agenda...

**Comment by andneuma** [comment]
Gibts die Möglichkeit, neben den Buttons das entsprechende icon anzuzeigen?

**Comment by kjoscha** [comment]
klar, wird aber ein bisschen klein, oder?

**Comment by kjoscha** [comment]
zumindest sollten dann einige Icons etwas vereinfacht werden, wie z.B. das von "Sports"...

**Comment by andneuma** [comment]
Stimmt, vielleicht lassen wir das erstmal
