### ISSUE TITLE
Map-Layout

### ISSUE THREAD

**Issue by andneuma** [kjoscha/lichtenberg#17]
Es wäre super sinnvoll, eine Maßstabsanzeige zu haben, damit man einschätzen kann, wie weit xyz entfernt ist.

Außerdem wäre es super, wenn der zoom beim lokalisieren nicht so stark wäre. Kannst du das noch nachregulieren?

**Comment by kjoscha** [comment]
> Es wäre super sinnvoll, eine Maßstabsanzeige zu haben, damit man einschätzen kann, wie weit xyz entfernt is

Easy, kommt bald

>Außerdem wäre es super, wenn der zoom beim lokalisieren nicht so stark wäre. Kannst du das noch nachregulieren?

japp. Funktioniert das Lokalisieren eigentlich bei dir einigermaßen? Ich glaub so richtig gut ist das nicht. Ich bekomme zB häufig die letzte WLAN-Position.

**Comment by kjoscha** [comment]
ScaleLine ist drin (musst evtl. deinen Cache löschen), wird noch lesbarer gemacht.

**Comment by andneuma** [comment]
cool! schriftart müsste schwarz sein

**Comment by andneuma** [comment]
lokalisierung hab ich immer nur zuause ausprobiert, da wars super

**Comment by andneuma** [comment]
Wärs nicht eigentlich auch cool, ein Suchfeld zu haben? Ich kann mir Situationen vorstellen, á la "Man hat einen Namen bekommen von einer Einrichtung, zu der man will, hat aber keine Ahnung wo die ist". Man gibt die im Suchfeld ein, wenn er was findet highlightet er den POI

**Comment by kjoscha** [comment]
ja, stimmt, das wäre cool!

**Comment by kjoscha** [comment]
wir müssen bald mal eine Prioliste machen oder so. Ich denke Nummer EIns ist langsam mal Mehrsprachigkeit, oder?

**Comment by andneuma** [comment]
Jo, seh ich auch beides so, das sollte gewährleistet sein, bevor wir das rauspusten, mindestens eng.
