### ISSUE TITLE
Piktogramme + "Piktogramm-Cloud"

### ISSUE THREAD

**Issue by kjoscha** [kjoscha/lichtenberg#3]
@andneuma Harter Frickelscheiß ist das eh, ist halt JavaScript ;) Ich habe hier mal ein Issue aufgemacht, damit es auf der Merkliste bleibt. Würde das als Nice-to-have bezeichnen. Alternativ fände ich es aber auch garnicht so schlecht für die Einfachheit der Seite, wenn immer nur eine Kategorie angezeigt wird + dazu ein extra Button "alles anzeigen". Was meinst du?

Andi schrieb:
>jo, hab jetzt einige gefunden unter: http://www.google.de/imgres?imgurl=http%3A%2F%2Fuxrepo.com%2Fstatic%2Ficon-sets%2Fopen-maps%2Fsvg%2Fsoccer.svg&imgrefurl=http%3A%2F%2Fuxrepo.com%2Ficon-sets%2Fopen-maps%2F2&h=580&w=580&tbnid=E_YDvNzj53Yq3M%3A&docid=290DQCxRo5VWWM&ei=bCQIVqasA4a2sQGU1b7gAQ&tbm=isch&iact=rc&uact=3&dur=2257&page=2&start=33&ndsp=40&ved=0CJkBEK0DMCdqFQoTCKaSh-7bl8gCFQZbLAodlKoPHA
lad ich ins repo rein, wenn ich zu allen bisherigen tags ausreichend gute pictograms gefunden habe.
cool wär ja sone pictogram-cloud zu machen an orten, wo es mehrere tags gibt. ist das möglich oder eher harter frickel-scheiß?"

**Comment by andneuma** [comment]
@kjoscha Ok, find ich nen guten Kompromissvorschlag! Aber verschiedene Icons zu verschiedenen tags is easy oder?

**Comment by kjoscha** [comment]
klar

**Comment by andneuma** [comment]
Allright, hab jetzt die icons als svg und png (90dpi) geadded. Wenn das blöd ist sag bescheid, dann scale ich die nochmal runter

**Comment by kjoscha** [comment]
so, ist nun drin, erstmal mit dem was da war...
