### ISSUE TITLE
Kategorien / Tags

### ISSUE THREAD

**Issue by kjoscha** [kjoscha/lichtenberg#4]
@andneuma Die bisher implementierten Kategorien habe ich nur mal so zum Testen genommen. Wir sollten mal überlegen, welche Kategorien sinnvoll sind und dabei IMO beachten, dass es nicht zu viele verschiedene werden.
Hatte deine Vorschläge leider auch vergessen. Vielleicht kannst du hier nochmal etwas dazu schreiben...

**Comment by andneuma** [comment]
@kjoscha jo, ok. außerdem brauchs für die tags insgesamt die columns "tags_ger", "tags_eng", "tags_[sprache_xyz]", tags dann entsprechend übersetzt

**Comment by kjoscha** [comment]
ja, kannst du einfach hinzufügen!

**Comment by andneuma** [comment]
Ok, es gibt jetzt category_ger und category_eng

**Comment by andneuma** [comment]
Erstmal bitte mögliche Tags auf

* DIY_repair_space / Selbsthilfewerkstatt
* Café / Café
* free Wifi (-> Symbol such ich noch raus und packs ins repo!) / kostenloses WLAN
* soccer_ground / Fußballplatz
* give_away_shop / Umsonstladen
* information center / Beratungsstelle
* urban_gardening / Kiezgarten

Reduzieren können wir das später immer noch, hab das aufm Schirm. Bis dahin fänd ich es aber cool, wenn die Sachen, die wir gemappt haben, also die jetzt im File stehen auch da auftauchen

**Comment by andneuma** [comment]
*push*, gern auch config-file machen, wo ich das dann selbst eintragen kann.

-> wär wichtig, weil sonst tauchen Sachen nicht auf, ich durchdenke wie gesagt die Reduzierung.

**Comment by kjoscha** [comment]
okay, Kategorien ändere ich heute

**Comment by kjoscha** [comment]
@andneuma , es ist ganz leicht, die Kategorien zu ändern. du musst nur diesen Array hier erweitern:
https://github.com/kjoscha/lichtenberg/blob/master/navigation.js#L34
Im Icon-Ordner muss eine PNG-File mit selbem Namen liegen. Ich schalte es heute abend so, dass bei Nicht-Übereinstimmung einfach ein Standardsymbol (Stern) angezeigt wird.

**Comment by kjoscha** [comment]
so, deine Änderungen sind deployed...

**Comment by andneuma** [comment]
Danke, neue Piktogramme sind in der Mache

**Comment by kjoscha** [comment]
Systemfehler Friedrichshain hat die Kategorien give_away_shop;event_room, diese gibt es aber garnicht mehr. Ist das richtig?

**Comment by andneuma** [comment]
ist richtig
