### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by andneuma** [kjoscha/lichtenberg#5]
Unterstützung unterschiedlicher Sprachen wäre super, vA erstmal Englisch und Deutsch. Dafür wäre es super, wenn man beim Aufruf der Seite nach der gewünschten Sprache gefragt wird. Um Textübersetzung würde ich mich kümmern

**Comment by kjoscha** [comment]
cool, dass du dich um Übersetzung kümmerst :+1: Für die Mehrsprachigkeit muss ich mal ein bisschen recherchieren und nach praktischen Wegen suchen. Oder hast du schon Ideen?
Betrifft ja immerhin Button-Beschriftung, JSON-Content und sonstigen "hartgecodeten" Content... das wird auf technischer Seite natürlich schnell unübersichtlich.

**Comment by kjoscha** [comment]
so wie hier hab ich es mir auch vorgestellt. ist natürlich schon etwas holprig, aber sooo viel gibt es ja dann auch nicht zu übersetzen:
http://foxable.net/2014/04/client-seitige-mehrsprachigkeit-mit-jquery/

**Comment by kjoscha** [comment]
ah, so ist es ja ganz schön: http://jsfiddle.net/mHAHz/1/

**Comment by andneuma** [comment]
Keine Ahnung von JS, das musst du entscheiden. Von meiner naiven Vorstellung aus muss ja nur einfach umgeschaltete werden, von welchen Spalten der content jeweils angezeigt wird, oder?

**Comment by kjoscha** [comment]
ja, genau. Aber das führt halt dazu, dass man z.B. einem Button-DIV nicht einfach einen Text geben kann, sondern den über eine js-Funktion reinladen muss. Das klappt aber schon. Setze mich voraussichtlich heute oder morgen abend mal ran...

**Comment by andneuma** [comment]
top!

**Comment by kjoscha** [comment]
@andneuma So, Englisch und deutsch sind jetzt umschaltbar. Bezieht sich nur noch nicht auf die POI-Beschreibungen - da wird Englisch angezeigt, wenn vorhanden, sonst deutsch... Editor ist auch nich englisch. Neue Sprachen, zumindest welche von links nach rechts laufen, sind nun einfach einzubauen.
