### ISSUE TITLE
Darstellung Texte in Boxen

### ISSUE THREAD

**Issue by andneuma** [kjoscha/lichtenberg#6]
Es wäre cool, wenn der Text in den Textboxen eine Formatierung bekäme. Muss nicht aufwendig sein, einfach ein paar Divs für die Spalten der json-Datei (Name, Beschreibung, Adresse, Tel., Email, ...), einfaches Stylesheet, fertig. Ist das easy für dich?

**Comment by kjoscha** [comment]
jow, das kommt natürlich... hatte so ein bisschen auf mehr Content gewartet, aber der ist ja nun da :)

**Comment by kjoscha** [comment]
to do: Formatierung der Description-Texte

**Comment by andneuma** [comment]
Cool wäre, wenn die Öffnungszeiten / opening times angezeigt werden könnten!

**Comment by kjoscha** [comment]
wird heute eingebaut

**Comment by kjoscha** [comment]
... :D

**Comment by andneuma** [comment]
Sieht für die libraries nicht so gut aus (Text verläuft über die Box-Grenze). Kann man in die Boxen nicht einzelne divs für 'opening hours' und Adresse einbauen? Zeilenumbrüche wären auch super.
