### ISSUE TITLE
Admin-Bereich mit Daten-Management

### ISSUE THREAD

**Issue by kjoscha** [kjoscha/lichtenberg#8]
Mittelfristig wäre es cool, aus der rein client-basierten Webseite eine kleine Webapp zu machen, die zumindest einen Single-User-Adminbereich hat, in dem man Features bearbeiten, löschen und hinzufügen kann. Die Daten sollten dafür am besten in einer Postgresql+Postgis-Datenbank liegen.

Ich versuche die Tage mal etwas mit PHP hinzumatschen...

Langfristig, vor allem wenn das Projekt ausgeweitet werden sollte, wäre natürlich ein richtiger Multi-User-Adminbereich cool.

**Comment by andneuma** [comment]
@kjoscha Auf jeden! Wobei die Kernthemen würde ich denken erstmal die momentan offenen issues sind! Oder hast du derbe Bock das grad zu basteln?

**Comment by kjoscha** [comment]
hab derbe bock mich ein wenig in server-kram einzuarbeiten ;) nee, werde aber vorher auf jeden fall den anderem kram machen...

**Comment by kjoscha** [comment]
@andneuma Einfacher Editor (hinzufügen und löschen von POI's) ist fertig und über den klitzekleinen Punkt oben rechts in der Navbar zu erreichen: http://kjoscha.lima-city.de/

Perspektivisch wäre natürlich das Editieren von Features schön und Passwortschutz wäre natürlich auch cool.

**Comment by kjoscha** [comment]
achso kannst gerne auf Herz und Nieren testen!

**Comment by kjoscha** [comment]
to do: edit fields

**Comment by andneuma** [comment]
Ist es dennoch weiterhin möglich, das csv- bzw. json-file zu editieren?

**Comment by kjoscha** [comment]
nicht mehr nötig. es kann nun editiert werden :) in den descriptions bitte erstmal noch plain text benutzen....

**Comment by kjoscha** [comment]
und giob mal feedback zur editierfunktion. habe es noch nicht ausführlich testen können

**Comment by kjoscha** [comment]
ich lass das Issue nochmal offen für Vorschläge/Bugs etc....

**Comment by kjoscha** [comment]
achso, @andneuma es wäre besser, die Daten nochmal neu einzugeben mit dem Formular, geht ja einfach per Copy-Paste. Umlaute funktionieren leider noch nicht (siehe Issue dazu).

**Comment by andneuma** [comment]
ok, mach ich

**Comment by andneuma** [comment]
In der Eingabemaske keine Unterteilung in categories_eng und _ger!

**Comment by andneuma** [comment]
Cancel Button wäre gut

**Comment by andneuma** [comment]
Für Anzeige, ob Übersetzung vorliegt oder nicht wäre es praktisch, wenn die description-fields unausgefüllt bleiben können (kann man dann besser abfragen)

**Comment by kjoscha** [comment]
stimmt

**Comment by andneuma** [comment]
"Back to map"-Button wäre gut

**Comment by kjoscha** [comment]
kommt natürlich auch ;)

**Comment by kjoscha** [comment]
@andneuma so, admin-Bereich ist jetzt mit Zurück-Button und viel übersichtlicher.

**Comment by andneuma** [comment]
Sehr cool, super!

**Comment by kjoscha** [comment]
>Für Anzeige, ob Übersetzung vorliegt oder nicht wäre es praktisch, wenn die description-fields unausgefüllt bleiben können (kann man dann besser abfragen)

done

**Comment by kjoscha** [comment]
So, im Adminbereich kann man nun ohne Passwort Orte vorschlagen (sie sind bisher noch direkt auf der Karte zu sehen. Ich baue es bald so, dass die im Adminbereich freigeschaltet werden müssen. Zudem muss das Captcha sich verändern nach jedem Hinzufügen). Den Adminbereich erreichen wir mit Nickname 'Admin' und dem gleichen Passwort wie vorher.

**Comment by kjoscha** [comment]
@andneuma leider habe ich dabei aus Versehen ein paar Datensätze gelöscht. Ich hatte aber zum Glück einen Dump gemacht, spiele die Daten morgen wieder rein...

**Comment by kjoscha** [comment]
Soooo, das Daten-Interface ist fertig! Jetzt kann es losgehen. Jede/r kann nun POI's hinzufügen, wir als Admins sehen die hinzugefügten Datensätze im Admin-Bereich und können sie über Checkboxen aktivieren. Sollte sich eigentlich alles von alleine erklären.

**Comment by andneuma** [comment]
Schick geworden, gleichzeitig simpel, gefällt mir sehr gut. I-Tüpfelchen wäre folgendes: Man hat sich lokalisieren lassen, also die aktuelle Lat/Lon bestimmen lassen. Jetzt will man genau diesen Punkt auf der Map eintragen lassen. Das geht bisher nicht, man müsste sich die Koordinaten irgendwie merken. cool wär also im Editierbereich ein Knopp bei Lat/Lon á la "receive from current position".

Außerdem das super-gimmick: adress from lat/lon (also reverse geocoding) und vice versa. Ersteres ist zB mit OSM und nem Python XML-Parser super einfach zu realisieren, weiß nich, wie sich das mit JS verhält,

**Comment by kjoscha** [comment]
>-Tüpfelchen wäre folgendes: Man hat sich lokalisieren lassen, also die aktuelle Lat/Lon bestimmen lassen.

Ich würde das gerne sogar noch schöner machen: Wenn auf "Add a Location" in der Map geklickt wird, soll man die Karte klicken und dann zum Formular mit entsprechend eingetragenen Koordinaten geleitet werden können.

> Außerdem das super-gimmick: adress from lat/lon (also reverse geocoding) und vice versa.

Jow, das steht aufm Plan, hab ich gestern auch ein Issue zu aufgemacht.

Was noch notwendig ist: Versions-Check bei gleichzeitiger Bearbeitung, so dass zwischenzeitlich von anderem user vorgenommene Änderungen nicht überschrieben werden... und die Möglichkeit, einen Namen einzugeben beim Hinzufügen eines Features.

**Comment by andneuma** [comment]
Jo, noch eine Idee für ein weiteres Feld: Bezirk. Wenn das ganze auf Berlin ausgeweitet wird brauchen wir irgendeine Unterteilung der POIs, sonst wirds alles unübersichtlich. Mein Vorschlag wäre also, die Liste der Pois nach Bezirken zu unterteilen.

**Comment by kjoscha** [comment]
hm, verstehe ich nicht so richtig. Ein Bezirk ist doch nur eine räumliche Einheit und die wechselt man doch durch das Schwenken der Karte...

**Comment by andneuma** [comment]
Genau, wenn man als editierender allerdings Änderungen an Eintrag XYZ machen will und da 500 Einträge sind ist das glaub ich praktischer weil schneller zu finden, oder?

**Comment by kjoscha** [comment]
Ahhh, es geht ums Admin-Interface :D Ja, klar, einfacher wäre aber, wenn man hier auch einfach nach Tags auswählen könnte, oder? Dann bräuchten wir kein neues Feld

**Comment by andneuma** [comment]
sorry, unklar ausgedrückt. Problem ist, dass manche POIs mehrere Tags besitzen. Fänd es eigentlich sorum auch cooler, allerdings wüsste ich nicht, wie man diese 1:n relation vernünftig darstellt (es sei denn man will, dass ein ding mehrfach angezeigt wird, halt unter den jeweiligen tags)

**Comment by kjoscha** [comment]
ja, das ist doch kein Problem, oder? Ich hätte mir das so vorgestellt, dass es oben Buttons zum Filtern gibt. Vielleicht müssen wir das aber garnicht so ausreifen, wenn zusätzlich an den Info-Fenstern zu jedem Feature ein Editier-Buttons angezeigt wird, der einen direkt zum Editierformular bringt?! Dürfte nicht zu schwierig sein zu implementieren....

**Comment by andneuma** [comment]
Find ich gut, mit den Buttons zum Filtern. Das editieren ist dann auf jeden Fall leicht, weil man kann einfach unter den in Frage kommenden Kateogorien xyz nachschauen, ob es das Ding schon gibt. Wär aber ein Zusatzfeature denke ich, solang kann man auch im Editierfenster mit Ctrl+F nach dem Namen suchen

**Comment by kjoscha** [comment]
So, nun kann man Orte mit Klick auf die Karte hinzufügen :) Einfach mal auf den "Add a place"-Button klicken und dann auf die Karte, das leitet dan weiter zum Formular mit eingetragenen Koordinaten...

**Comment by kjoscha** [comment]
@andneuma bäm, jetzt auch mit geocoding
